### ISSUE TITLE
Icon tooltip is not localized

### ISSUE THREAD

**Issue by fkaelberer** [cpeterso/open-page-in-private-window#4]
![grafik](https://user-images.githubusercontent.com/4624768/44311819-99a3e880-a3ee-11e8-9b1b-0d63c6ea1cce.png)
- Expected behavior: Icon tooltip text is the same as in the right-click menu ("Seite in privatem Fenster öffnen")
- Actual behavior: English text is shown.

(I hope the tooltip icon isn't just saying the name of the addon because the tooltips of all other icons are describing the corresponding action.)

**Comment by cpeterso** [comment]
Thanks for the bug report. The tooltip ought to be localized like the right-click menu item. I should fix that.

> I hope the tooltip icon isn't just saying the name of the addon because the tooltips of all other icons are describing the corresponding action.

What tooltip description would you like to see? In English, "Open Page in Private Window" is both the extension name and the action. 😃

**Comment by fkaelberer** [comment]
> What tooltip description would you like to see?

The right-click menu entry translation is just fine (It's the direct translation of "Open Page in Private Window").

**Comment by cpeterso** [comment]
I published a new extension version (v1.0.0!) that should uses the same localized string for the context menu item and the toolbar icon's tooltip. I didn't localize the extension name at this time. Are extension names commonly localized?

https://addons.mozilla.org/en-US/firefox/addon/open-page-in-private-window/versions/?page=1#version-1.0.0

Thanks again for reporting this bug!

**Comment by fkaelberer** [comment]
Translation is displayed fine now, but there was a grammatical error in the localization. See #7.
